### ISSUE TITLE
Update Gifs with Images

### ISSUE THREAD

**Issue by HooriaHIC** [HooriaHIC/weatherapp#1]
In Script.js file, theres alot of different gif used for diffrrent weather, change all those gifs into proper weather images.
Also, you can see the weather name on top of the gif(so you can find images of the weather by there names) :)

**Comment by malaikaIshtiaq** [comment]
I want to work on this issue @HooriaHIC

**Comment by HooriaHIC** [comment]
Sure, Go ahead 😊

**Comment by HooriaHIC** [comment]
I've merged your PR :)
